ALTER TABLE users
    ADD COLUMN IF NOT EXISTS roll_no   VARCHAR(50),
    ADD COLUMN IF NOT EXISTS semester  VARCHAR(20),
    ADD COLUMN IF NOT EXISTS batch     VARCHAR(50),
    ADD COLUMN IF NOT EXISTS course    VARCHAR(100),
    ADD COLUMN IF NOT EXISTS stream    VARCHAR(100);
